### ISSUE TITLE
py3.11 bug

### ISSUE THREAD

**Issue by nufeng1999** [LoveDaisy/tetris_game#5]
Traceback (most recent call last):
  File "/home/nufeng/tetris_game/tetris_game.py", line 178, in paintEvent
    drawSquare(painter, x * self.gridSize + dx, y * self.gridSize + dy, val, self.gridSize)
  File "/home/nufeng/tetris_game/tetris_game.py", line 148, in drawSquare
    painter.fillRect(x + 1, y + 1, s - 2, s - 2, color)
TypeError: arguments did not match any overloaded call:
  fillRect(self, a0: QRectF, a1: Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, a1: Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRectF, color: Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, color: Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, preset: QGradient.Preset): argument 1 has unexpected type 'float'

**Comment by Koisu-unavailable** [comment]
skill issue
